name: Pull Request CI

on:
  pull_request_target:
    branches: [ master ]

jobs:
  lint:
    name:  Run Kotlin Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: chmod +x gradlew
      - run: ./gradlew ktlintFormat

  tests:
    name: Run Kotlin Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: chmod +x gradlew
      - run: ./gradlew clean test --stacktrace

  build:
    name: Build JAR
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: chmod +x gradlew
      - run: ./gradlew clean build -x test